"""
Machine Learning Module for Health Content Search
==================================================

This module contains two TensorFlow models for improving search relevance:

1. Embedding Model (embedding_model.py) - Semantic search
2. Ranking Model (ranking_model.py) - Learning-to-rank


EMBEDDING MODEL
---------------

Purpose:
    Converts text into numerical vectors (embeddings) that capture semantic meaning.
    Similar texts will have similar vectors, enabling "semantic search" where
    results match the meaning of a query, not just keywords.

    Example: A search for "hodepine" could find content about "migrene" even if
    the word "hodepine" doesn't appear in the text.

Training data:
    - Source: Content corpus from MySQL database (content table)
    - NOT trained on user logs
    - Requires content cached from Helsedir API

How it works:
    1. Text is tokenized into words/subwords
    2. Each token is converted to a learned embedding vector
    3. A Bidirectional LSTM processes the sequence
    4. Output is a fixed-size vector (default: 256 dimensions)
    5. Vectors are L2-normalized for cosine similarity

Training process:
    python scripts/train_embedding_model.py

    The script:
    1. Loads content from MySQL database
    2. Builds vocabulary from the corpus
    3. Creates the model architecture
    4. Saves to models/embedding/model.keras

Usage in search:
    When ML_EMBEDDING_ENABLED=true:
    1. On startup, all content is pre-embedded
    2. For each search, the query is embedded
    3. Cosine similarity is computed between query and all content
    4. Semantic scores are combined with keyword scores

Limitations:
    - Requires content to be cached in database
    - Model quality depends on corpus size and diversity
    - Initial training can be slow for large corpora


RANKING MODEL
-------------

Purpose:
    Re-ranks search results based on learned user preferences.
    Uses click data to learn which results users find most relevant
    for different types of queries.

    Example: If users consistently click the 3rd result for "diabetes" queries,
    the model learns to rank that content higher.

Training data:
    - Source: MySQL database (search_logs, search_results_shown, click_logs tables)
    - Requires both search events (with results_shown) and click events
    - search_id links searches to their clicks (required!)
    - Only searches with at least one click are used for training
    - More data = better model

Database tables:
    search_logs:
        - search_id: UUID linking to clicks
        - query: search query
        - role: user role (optional)
        - results_count: number of results shown
        - timestamp: when search occurred

    search_results_shown:
        - search_id: foreign key to search_logs
        - content_id: which content was shown
        - position: position in results (0-indexed)
        - score: baseline score

    click_logs:
        - search_id: links to originating search
        - content_id: which content was clicked
        - position: position when clicked
        - query: original query
        - role: user role

    IMPORTANT: search_id must be a UUID generated by the frontend for each
    search. The same search_id must be used when logging clicks on results
    from that search. This correctly links clicks to their originating search,
    even if the user searches multiple times before clicking.

How it works:
    1. Searches without clicks are ignored (user may have refined query)
    2. For each search with clicks, results are labeled:
       - Clicked result → positive (label=1)
       - Shown but not clicked → negative (label=0)
    2. Features are extracted for each result:
       - Keyword match scores
       - Semantic similarity (if embedding model available)
       - Content metadata (type, age)
       - Historical click-through rate
    3. Neural network learns to predict click probability
    4. Results are re-ranked by predicted relevance

Training process:
    python scripts/train_ranking_model.py

    The script:
    1. Loads search and click events from MySQL database
    2. Creates training examples (positive/negative pairs)
    3. Trains the ranking model
    4. Saves to models/ranking/model.keras

    Minimum recommended: 100+ search sessions with clicks

Usage in search:
    When ML_RANKING_ENABLED=true:
    1. Baseline search returns initial results
    2. Features are extracted for each result
    3. Ranking model predicts relevance scores
    4. Results are re-ordered by predicted score

Limitations:
    - Requires sufficient click data (cold start problem)
    - Biased towards already-clicked content (popularity bias)
    - May not generalize well to new content


RECOMMENDED IMPLEMENTATION ORDER
--------------------------------

Phase 1: Data Collection (Start immediately)
    - Enable extended logging in frontend
    - Log search_id, results_shown on every search
    - Log search_id, position on every click
    - Collect data for weeks/months

Phase 2: Ranking Model (When ~100+ searches with clicks)
    - Train ranking model on collected data
    - Set ML_RANKING_ENABLED=true
    - Monitor and retrain periodically

Phase 3: Embedding Model (If local content available)
    - Cache Helsedir content in database
    - Train embedding model on content
    - Set ML_EMBEDDING_ENABLED=true
    - Combine semantic + keyword + ranking scores


CONFIGURATION
-------------

Environment variables (.env):

    # Enable/disable models
    ML_EMBEDDING_ENABLED=false  # Set true after training embedding model
    ML_RANKING_ENABLED=false    # Set true after training ranking model

    # Model storage location
    ML_MODELS_DIR=models

    # MySQL Database (for training data)
    MYSQL_HOST=localhost
    MYSQL_PORT=3306
    MYSQL_USER=your_user
    MYSQL_PASSWORD=your_password
    MYSQL_DATABASE=helsedir_ai


FILE STRUCTURE
--------------

    app/ml/
    ├── __init__.py           # This file - documentation
    ├── embedding_model.py    # TensorFlow embedding model class
    └── ranking_model.py      # TensorFlow ranking model class

    models/
    ├── embedding/
    │   └── model.keras       # Trained embedding model
    └── ranking/
        └── model.keras       # Trained ranking model

    scripts/
    ├── train_embedding_model.py  # Embedding training script
    └── train_ranking_model.py    # Ranking training script
"""
