"""
Logging request DTOs.
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime


class SearchResultLog(BaseModel):
    """Single search result in a logged search event."""
    content_id: str
    position: int
    score: float


class LogRequest(BaseModel):
    """Request model for logging endpoint."""
    event_type: str = Field(..., pattern="^(search|click|role_change)$")
    query: Optional[str] = None
    content_id: Optional[str] = None
    role: Optional[str] = None
    timestamp: Optional[datetime] = None
    # Fields for learning-to-rank data collection
    search_id: Optional[str] = Field(None, description="Unique ID linking search and click events (UUID generated by frontend)")
    position: Optional[int] = Field(None, description="Position of clicked result (for click events)")
    results_shown: Optional[List[SearchResultLog]] = Field(None, description="Results shown to user (for search events)")
